# Website details

site_name: ERC Handbook
site_url: https://erc-bpgc.github.io/handbook/

site_description: A beginners guide to all things robotics
site_author: Electronics and Robotics Club (ERC), BITS Goa

copyright: 'Copyright &copy; 2020 Electronics and Robotics Club (ERC), BITS Goa'


# mkdocs setup

theme:
  name: 'material'
  language: en
  icon:
    logo: material/book-open-page-variant
  favicon: images/erc_logo.png
  features:
    - tabs
  palette:
    primary: green
    accent: green

repo_name: 'handbook'
repo_url: 'https://github.com/ERC-BPGC/handbook'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/erc_bpgc

    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ElectronicsAndRoboticsClub

    - icon: fontawesome/brands/github
      link: https://github.com/ERC-BPGC

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/electronics-robotics-club-bits-goa/

markdown_extensions:
  - attr_list
  - smarty
  - admonition
  - codehilite
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

google_analytics:
  - UA-173174352-1
  - auto


# navigation bar

nav:
  - Home: index.md

  - Overview:
    - What is Robotics?: overview/what_is_robotics.md
    - Key Areas: overview/key_areas.md
    - Reference Material: overview/reference_material.md

  - Automation:
    - Introduction: automation/intro.md
    - ROS:
      - Setting Up: automation/ROS/setting_up.md
      - Getting Started with ROS: automation/ROS/ros.md
      - ROS Parameters: automation/ROS/ros_p2.md

  - Electronics:
    - Introduction: electronics/intro.md
    - Basic Electronic Components: 
      - Breadboard: electronics/Basic_Electronic_Components/breadboard.md
    - Development Boards:
      - Arduino: electronics/Development_Boards/Arduino.md   

  - Mechanical:
    - Introduction: mechanical/intro.md

  - Simulation:
    - Introduction: simulation/intro.md
    - Gazebo:
      - Basics of Gazebo: simulation/gazebo/basics.md

  - About Us: about.md
  
  - Miscellaneous Resources: misc.md

  - Updates: CHANGELOG.md
