# Website details

site_name: ERC Handbook
site_url: https://erc-bpgc.github.io/handbook/

site_description: A beginners guide to all things robotics
site_author: Electronics and Robotics Club (ERC), BITS Goa

copyright: 'Copyright &copy; 2020 Electronics and Robotics Club (ERC), BITS Goa'


# mkdocs setup

theme:
  name: 'material'
  language: en
  icon:
    logo: material/book-open-page-variant
  favicon: images/logo.png
  features:
    - tabs
  palette:
    primary: green
    accent: green

repo_name: 'handbook'
repo_url: 'https://github.com/ERC-BPGC/handbook'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/erc_bpgc

    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ElectronicsAndRoboticsClub   

    - icon: fontawesome/brands/github
      link: https://github.com/ERC-BPGC

    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/erc_bitsgoa/  

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/electronics-robotics-club-bits-goa/

markdown_extensions:
  - attr_list
  - smarty
  - admonition
  - codehilite
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

google_analytics:
  - UA-173174352-1
  - auto


# navigation bar

nav:
  - Home: index.md

  - Overview:
    - What is Robotics?: overview/what_is_robotics.md
    - Key Areas: overview/key_areas.md
    - Reference Material: overview/reference_material.md

  - Automation:
    - Introduction: automation/intro.md
    - ROS:
      - Setting Up: automation/ROS/setting_up.md
      - Getting Started with ROS: automation/ROS/ros.md
      - ROS Parameters: automation/ROS/ros_p2.md
    - Path Planning:
      - Introduction to Path Planning in Robotics: automation/PathPlanners/intro.md
      - Graph Based Algorithms:
        - A Star: automation/PathPlanners/Astar.md
        - Dijkstra's Algorithm: automation/PathPlanners/Dijkstra.md
      - Sampling Based Algorithms:
        - RRT: automation/PathPlanners/RRT.md
    - Control Theory:
      - Introduction to Control Theory: automation/ControlTheory/Control_Theory.md
      - PID Controller: automation/ControlTheory/PID_Controller.md
      - Linear Quadratic Regulator: automation/ControlTheory/LQR.md
      - Model Predictive Control: automation/ControlTheory/MPC.md
      
  - Electronics:
    - Introduction: electronics/intro.md
    - Basic Electronic Components: 
      - Breadboard: electronics/Basic_Electronic_Components/breadboard.md
    - Development Boards:
      - Arduino: electronics/Development_Boards/Arduino.md
      - BluePill (STM32F103C8T6) : electronics/Development_Boards/STM32.md
      - Arduino vs STM32 : electronics/Development_Boards/STM32vsArduinoUNO.md
 
  - Mechanical:
    - Introduction: mechanical/intro.md
    - Gears: mechanical/Gears.md
    - Kinematics and Dynamics:
          - Position and Orientation: mechanical/position and orientation.md
          - Kinematics:
                - Joint Kinematics: mechanical/Joint Kinematics.md
                - Forward and Inverse Kinematics: mechanical/Forward and Inverse Kinematics.md
          - Dynamics:
                - Introduction to Dynamics: mechanical/Introduction to Dynamics.md

  - Simulation:
    - Introduction: simulation/intro.md
    - Gazebo:
      - Basics of Gazebo: simulation/gazebo/basics.md
    - STDR Simulator:
      - Basics of STDR: simulation/stdr/Basics.md

  - About Us: about.md
  
  - Miscellaneous Resources: misc.md

  - Updates: CHANGELOG.md
